let csrf = '', selected = '', currentStatus = {state:'loading'}, logEntries = [];
const $ = selector => document.querySelector(selector);
const escapeHTML = value => { const node = document.createElement('div'); node.textContent = value || ''; return node.innerHTML };
const escapeAttr = value => escapeHTML(value).replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const duration = startedAt => { if(!startedAt)return '';const seconds=Math.max(0,Math.floor((Date.now()-new Date(startedAt).getTime())/1000));const h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return `${h}:${m}:${s}` };
const parseRoutes = value => value.split(/[\s,]+/).map(x=>x.trim()).filter(Boolean);
async function req(path, options = {}) { options.headers = {...options.headers, 'X-CSRF-Token': csrf}; const response = await fetch(path, options); if (!response.ok) throw new Error(await response.text()); return response.status === 204 ? null : response.json() }
async function refresh() {
  const [status, response] = await Promise.all([req('/api/v1/status'), req('/api/v1/profiles')]); const profiles = Array.isArray(response) ? response : [];
  currentStatus = status;
  if (!selected && profiles.length) selected = profiles[0].id;
  $('#state').textContent = status.state; $('#statusMark').className = 'mark ' + status.state;
  const busy = ['connecting','connected','disconnecting'].includes(status.state);
  $('#profiles').innerHTML = profiles.map(p => { const active=p.id===status.profileId; const connected=active&&status.state==='connected'; const pending=active&&status.state==='connecting'; const ruleCount=(p.routeAdditions?.length||0)+(p.routeDeletions?.length||0); return `<div class="profile ${p.id===selected?'selected':''} ${connected?'active':''}" data-select="${p.id}"><div class="profile-copy"><b>${escapeHTML(p.name)}</b>${connected?`<span class="profile-state"> Active · <span data-uptime>${duration(status.startedAt)}</span></span>`:pending?'<span> · Connecting…</span>':''}<p>${escapeHTML(p.server)}${p.verbose ? ' · verbose' : ''}${ruleCount ? ` · ${ruleCount} saved route rules` : ''}${p.macAddress ? ' · ' + escapeHTML(p.macAddress) : ''}</p></div><div>${active&&busy?`<button class="ghost" data-disconnect>Disconnect</button>`:`<button data-connect="${p.id}" ${busy?'disabled':''}>Connect</button>`} <button class="ghost" data-edit="${p.id}">Edit</button> <button class="ghost" data-profile-delete="${p.id}" data-profile-name="${escapeAttr(p.name)}" ${active&&busy?'disabled':''}>Delete</button></div></div>` }).join('') || '<p class="hint">No profiles yet.</p>';
}
async function loadRoutes() { const response = await req('/api/v1/routes'); const routes = Array.isArray(response) ? response : []; $('#routes').innerHTML = routes.map(r => `<div class="route"><span class="source">${escapeHTML(r.source)}</span><input value="${escapeHTML(r.cidr)}" data-route-value="${r.id}"><div><button data-route-save="${r.id}">Save</button> <button class="ghost" data-route-delete="${r.id}">Delete</button></div></div>`).join('') || '<p class="hint">No routes received yet.</p>' }
function renderLogs() { const search=$('#logSearch').value.toLowerCase();$('#logs').textContent=logEntries.filter(e=>!search||`${e.level} ${e.component} ${e.message}`.toLowerCase().includes(search)).map(e=>`${e.time} [${e.level}] ${e.component}: ${e.message}`).join('\n');$('#logs').scrollTop=$('#logs').scrollHeight }
function log(entry) { logEntries.push(entry);if(logEntries.length>2000)logEntries=logEntries.slice(-2000);renderLogs() }
async function openAuth(id) { selected = id; const p = await req('/api/v1/profiles/' + id); $('#auth form').reset(); $('#authUsername').value = p.username || ''; $('#password').placeholder = p.passwordSet ? 'Saved in Keychain — leave blank to use' : 'Password'; $('#authHint').textContent = p.passwordSet ? 'The saved password will be used when this field is blank. OTP is never saved.' : 'Enter the password to connect. OTP is never saved.'; $('#auth').showModal() }
async function openEditor(id) { const p = await req('/api/v1/profiles/' + id); for (const key of ['id','name','username','protocol']) $('#' + key).value = p[key] || ''; $('#url').value = p.server; $('#macAddress').value = p.macAddress || ''; $('#verbose').checked = !!p.verbose; $('#routeAdditions').value=(p.routeAdditions||[]).join('\n');$('#routeDeletions').value=(p.routeDeletions||[]).join('\n'); $('#profilePassword').value = ''; $('#profilePassword').placeholder = p.passwordSet ? 'Saved in Keychain — leave blank to keep' : 'Enter password to save'; $('#editor').showModal() }
document.addEventListener('click', async event => { try { const d = event.target.dataset; const row=event.target.closest('[data-select]');if(row&&!event.target.closest('button')&&!['connecting','connected','disconnecting'].includes(currentStatus.state)){await openAuth(row.dataset.select)} if (d.connect) await openAuth(d.connect); if (d.disconnect!==undefined) { await req('/api/v1/disconnect',{method:'POST'}); await refresh() } if (d.edit) await openEditor(d.edit); if (d.profileDelete && confirm(`Delete profile “${d.profileName}”? The saved Keychain password will also be removed.`)) { await req('/api/v1/profiles/'+d.profileDelete,{method:'DELETE'});if(selected===d.profileDelete)selected='';await refresh() } if (d.routeSave) { const input = document.querySelector(`[data-route-value="${d.routeSave}"]`); await req('/api/v1/routes/' + d.routeSave, {method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({cidr:input.value})}); await loadRoutes() } if (d.routeDelete) { await req('/api/v1/routes/' + d.routeDelete, {method:'DELETE'}); await loadRoutes() } } catch (error) { alert(error.message) } });
$('#new').onclick = () => { $('#editor form').reset(); $('#id').value = ''; $('#profilePassword').placeholder = 'Enter password to save'; $('#editor').showModal() };
$('#editorCancel').onclick = () => $('#editor').close();
$('#authCancel').onclick = () => { $('#password').value=''; $('#otp').value=''; $('#auth').close() };
$('#clear').onclick = () => { logEntries=[]; renderLogs() };
$('#logSearch').oninput = renderLogs;
$('#authenticate').onclick = async event => { event.preventDefault(); const button=$('#authenticate'),username=$('#authUsername').value,password=$('#password').value,otp=$('#otp').value; button.disabled=true;button.textContent='Connecting…'; try { await req('/api/v1/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:selected,username,password,otp})}); $('#password').value='';$('#otp').value='';$('#auth').close();await refresh() } catch(error) { $('#password').value='';$('#otp').value='';alert(error.message) } finally { button.disabled=false;button.textContent='Connect' } };
$('#addRoute').onclick = async () => { try { await req('/api/v1/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cidr:$('#newRoute').value})});$('#newRoute').value='';loadRoutes() } catch(error) { alert(error.message) } };
$('#exportRoutes').onclick = () => { if(!selected)return alert('Select a profile first');const link=document.createElement('a');link.href='/api/v1/routes-export?profileId='+encodeURIComponent(selected);link.download='openconnect-custom-routes.json';link.click() };
$('#diagnostics').onclick = async () => { try { const response=await fetch('/api/v1/diagnostics',{method:'POST',headers:{'X-CSRF-Token':csrf}});if(!response.ok)throw new Error(await response.text());const link=document.createElement('a');link.href=URL.createObjectURL(await response.blob());link.download='openconnect-diagnostics.zip';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000) } catch(error) { alert(error.message) } };
$('#save').onclick = async event => { event.preventDefault(); const p={id:$('#id').value,name:$('#name').value,server:$('#url').value,username:$('#username').value,protocol:$('#protocol').value,password:$('#profilePassword').value,macAddress:$('#macAddress').value,verbose:$('#verbose').checked,routeAdditions:parseRoutes($('#routeAdditions').value),routeDeletions:parseRoutes($('#routeDeletions').value)}; try { await req('/api/v1/profiles'+(p.id?'/'+p.id:''),{method:p.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});$('#profilePassword').value='';$('#editor').close();refresh() } catch(error) { $('#profilePassword').value='';alert(error.message) } };
async function init() { csrf=(await req('/api/v1/session')).csrfToken;await refresh();const response=await req('/api/v1/logs');logEntries=Array.isArray(response)?response:[];renderLogs();await loadRoutes();const events=new EventSource('/api/v1/events');events.onmessage=event=>{const entry=JSON.parse(event.data);log(entry);if(entry.component==='Routing')loadRoutes()};setInterval(refresh,2000);setInterval(()=>document.querySelectorAll('[data-uptime]').forEach(node=>node.textContent=duration(currentStatus.startedAt)),1000) }
init().catch(error => alert(error.message));
